__title__ = "videohash"
__description__ = "videohash is a video fingerprinting / video hashing tool written in Python"
__url__ = "https://akamhy.github.io/videohash/"
__version__ = "1.0.7"
__author__ = "akamhy"
__author_email__ = "akamhy@yahoo.com"
__license__ = "MIT"
__copyright__ = "Copyright 2021 Akash Mahanty et al."
