__title__ = "videohash"
__description__ = "A Python Perceptual Video Hashing/Fingerprinting Package"
__url__ = "https://akamhy.github.io/videohash/"
__version__ = "2.0.0"
__author__ = "Akash Mahanty"
__author_email__ = "akamhy@yahoo.com"
__license__ = "MIT"
__copyright__ = "Copyright 2021 Akash Mahanty et al."
